### ISSUE TITLE
Broken on Angular Material 13

### ISSUE THREAD

**Issue by mruknowme** [johannesjo/angular-material-css-vars#85]
Updating to Angular 13 breaks sass compilation with the following errors:

```text
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material'as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/angular-material-css-vars/_main.scss 1:1  @import
  apps/dashboard/src/styles.scss 1:9                     root stylesheet

./apps/dashboard/src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material'as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/angular-material-css-vars/_main.scss 1:1  @import
  apps/dashboard/src/styles.scss 1:9                     root stylesheet
    at tryRunOrWebpackError (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4963:12)
    at __webpack_require__ (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4920:18)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4991:20
    at symbolIterator (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3485:9)
    at done (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4898:43
    at symbolIterator (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3463:5)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4863:16
    at symbolIterator (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3485:9)
    at timesSync (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3463:5)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material'as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/angular-material-css-vars/_main.scss 1:1  @import
  apps/dashboard/src/styles.scss 1:9                     root stylesheet
    at Object.<anonymous> (/Users/max/Demonz/Projects/my-app-name/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[1]!/Users/max/Demonz/Projects/my-app-name/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[2]!/Users/max/Demonz/Projects/my-app-name/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[4].rules[1].use[0]!/Users/max/Demonz/Projects/my-app-name/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].rules[1].use[1]!/Users/max/Demonz/Projects/my-app-name/apps/dashboard/src/styles.scss:1:7)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:432:11
    at Hook.eval [as call] (eval at create (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/Hook.js:14:14)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4965:39
    at tryRunOrWebpackError (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4963:12)
    at __webpack_require__ (/Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4920:18)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4991:20
    at symbolIterator (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3485:9)
    at done (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/max/Demonz/Projects/my-app-name/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/max/Demonz/Projects/my-app-name/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4898:43
    at symbolIterator (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/max/Demonz/Projects/my-app-name/node_modules/neo-async/async.js:2297:7)

Generated code for /Users/max/Demonz/Projects/my-app-name/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[1]!/Users/max/Demonz/Projects/my-app-name/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[2]!/Users/max/Demonz/Projects/my-app-name/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[4].rules[1].use[0]!/Users/max/Demonz/Projects/my-app-name/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].rules[1].use[1]!/Users/max/Demonz/Projects/my-app-name/apps/dashboard/src/styles.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n  ╷\n1 │ @use '~@angular/material'as mat;\n  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  ╵\n  node_modules/angular-material-css-vars/_main.scss 1:1  @import\n  apps/dashboard/src/styles.scss 1:9                     root stylesheet");
```

**Comment by vpetrusevici** [comment]
The same error. Looks like material changed scss again)

**Comment by vpetrusevici** [comment]
https://github.com/angular/components/issues/23889

**Comment by johannesjo** [comment]
Angular 13 is not yet supported. PRs dealing with this are welcome!

**Comment by vpetrusevici** [comment]
> Angular 13 is not yet supported. PRs dealing with this are welcome! Demo works, lib build successful.
You're welcome! :)

**Comment by vpetrusevici** [comment]
@johannesjo  You're welcome! :) Demo works, lib build is successful.

**Comment by vpetrusevici** [comment]
@johannesjo Important change that i missed is scss imports.
I changed builder to @angular-devkit/build-angular:ng-packagr, so now scss can be imported like this
`@import "~angular-material-css-vars/src/lib/public-util";`
instead of 
`@import "~angular-material-css-vars/public-util";`
Sorry. I noticed this only after updating the dependencies of my project.

**Comment by johannesjo** [comment]
@vpetrusevici I don't quite understand as I can't find any any occurrences of that import.

**Comment by vpetrusevici** [comment]
![image](https://user-images.githubusercontent.com/40790510/140556552-d0c31760-e853-4d7a-9532-e1e78ff4dcef.png)
These files were in main folder before, but now ther are here.

Because of this change 
![image](https://user-images.githubusercontent.com/40790510/140556795-9ff709e1-36ca-4761-9c24-c414c9daf259.png)

**Comment by mruknowme** [comment]
Big thanks to @vpetrusevici for making a pull request so promptly and to @johannesjo for approving it. I can confirm it works npw for Material v13.0.0.
I had to use import `@import '~angular-material-css-vars/src/lib/main';` not sure what was a reference to `public-util` about

**Comment by vpetrusevici** [comment]
> Big thanks to @vpetrusevici for making a pull request so promptly and to @johannesjo for approving it. I can confirm it works npw for Material v13.0.0. I had to use import `@import '~angular-material-css-vars/src/lib/main';` not sure what was a reference to `public-util` about

It was about all scss files. They just changed location after builder update.

**Comment by johannesjo** [comment]
> It was about all scss files. They just changed location after builder update.

If this is the only complication, I think we're all fine! Or is there anything I can do to improve this @vpetrusevici ?

Anyway, thank you very much again @vpetrusevici  !! Great job!
